### PR TITLE
Update the licenses and license exceptions lists with SPDX 2.4

### PR DESCRIPTION
**Pull request by breard-r**
The licenses and license exceptions lists were out-of-date: some items
were missing and a few were deprecated, causing valid licenses to be
rejected.
https://spdx.org/licenses/index.html
https://spdx.org/licenses/exceptions-index.html

PS: it would be nice if a new release was made after this change! :-)

### CODE REVIEW

**Comment by withoutboats** [comment]
Thanks for the PR. Is there a strong reason to remove deprecated licenses? This crate's main client is the crates.io backend, which uses it to validate all of the licenses of crates uploaded to crates.io. I don't think crates.io could update to a version of this crate which removed any licenses.

Sorry for taking a while to triage this.

**Comment by breard-r** [comment]
> Is there a strong reason to remove deprecated licenses?

All the "GPL-X.0-with-Y-exception" licenses and "WXwindows" are not really removed. They have been deprecated because they are not real licences, they are licences with an exception and therefore should be noted as such. For example, "GPL-2.0 WITH Font-exception-2.0" should be used in place of "GPL-2.0-with-font-exception". The thing is some exceptions ave several versions (eg: autoconf and GCC), which would cause the creation multiple new "fake licenses" to be exhaustive. Because the current deprecated "fake licenses" are not exhaustive, unclear about the version of the exception and should be written under a new form, I think it is best to remove them.

References:
- [GPL-2.0-with-GCC-exception](https://spdx.org/licenses/GPL-2.0-with-GCC-exception)
- [GPL-2.0-with-autoconf-exception](https://spdx.org/licenses/GPL-2.0-with-autoconf-exception)
- [GPL-2.0-with-bison-exception](https://spdx.org/licenses/GPL-2.0-with-bison-exception)
- [GPL-2.0-with-classpath-exception](https://spdx.org/licenses/GPL-2.0-with-classpath-exception)
- [GPL-2.0-with-font-exceptio](https://spdx.org/licenses/GPL-2.0-with-font-exception)
- [GPL-3.0-with-GCC-exception](https://spdx.org/licenses/GPL-3.0-with-GCC-exception)
- [GPL-3.0-with-autoconf-exception](https://spdx.org/licenses/GPL-3.0-with-autoconf-exception)
- [wxWindows](https://spdx.org/licenses/WXwindows)

Now about "StandardML-NJ" license, it should be remove because it is in fact a duplicate of the "SMLNJ" license ([source](https://spdx.org/licenses/StandardML-NJ)).

> I don't think crates.io could update to a version of this crate which removed any licenses.

I have just downloaded [crates.io index](https://github.com/rust-lang/crates.io-index) and used the [license survey script](https://github.com/pwoolcoc/crates.io-license-survey) to look for crates using any of the deprecated licenses. I was unable to find any:

``` console
$ wc -l license.csv
5434 license.csv
$ for license_tag in "GPL-2.0-with-" "GPL-3.0-with-" "wxWindows" "StandardML-NJ"; do grep -i "$license_tag" license.csv | wc -l; done 
0
0
0
0
```

**Comment by withoutboats** [comment]
Seeing that there are no licenses which would break on crates.io is reassuring. What do you think about separating this into two PRs, though, one to add the new licenses and one to remove the deprecated ones?

Technically, both are "breaking changes" by a strict interpretation, but I think accepting more licenses can be performed on a minor semver bump, whereas rejecting licenses requires a major bump. We can land the addition with a minor bump and update crates.io's dependency, to get the new licenses in ASAP, and then make sure that crates.io wants to accept removing the deprecated licenses before deciding to update crates.io to I guess the 2.0.0 version of this library.

**Comment by breard-r** [comment]
> What do you think about separating this into two PRs, though, one to add the new licenses and one to remove the deprecated ones?

Good idea! I created a second PR with only the new licenses so it can be merged. This one could be merged later to remove the deprecated licenses.

**Comment by withoutboats** [comment]
I've merged the purely additive PR, uploaded a new version to crates.io, and opened a PR to the crates.io repo to make sure that it uses the current version of this crate. Soliciting feedback from them on whether or not they want to exclude deprecated licenses (since they're the primary client of this lib).

**Comment by wking** [comment]
> Soliciting feedback from them on whether or not they want to exclude deprecated licenses (since they're the primary client of this lib).

As of last year, crates.io was [ok with dropping deprecated but unused identifiers][1].  It looks like [you intended to merge this][2] and cut a 2.0, but that fell off the radar?  If you're still interested in doing that, it's probably worth re-checking to see if the deprecated identifiers are still unused.

[1]: https://github.com/rust-lang/crates.io/pull/385#issuecomment-233014202
[2]: https://github.com/rust-lang/crates.io/pull/385#issuecomment-233774750

**Comment by wking** [comment]
I think we want to keep deprecated licenses here so folks have time to migrate to newer versions (e.g. see rust-lang/cargo#4888).  We can drop them once SPDX drops them, unless crates.io and other consumers have a good argument for extending a deprecation period beyond what SPDX thought was necessary.  I'm closing this PR (whose only remaining changes are removing the deprecated licenses).  And things like #11 will make it easier to stay up to date in the future.

**Pull request closed without merging**
