### PR TITLE
Update to version 3.6 of the SPDX license list

### PR DESCRIPTION
**Pull request by kemitchell**
This PR updates the license list to version 3.6, and bumps the appropriate version numbers throughout metadata and documentation.

Full Disclosure: Two licenses that I worked on, `Parity-6.0.0` and `BlueOak-1.0.0`, were identified by SPDX in version 3.6. I am a member of Blue Oak Council and the sole member-manager of Artless Devices, the company behind License Zero, which stewards Parity.

### CODE REVIEW

**Comment by carols10cents** [comment]
Hi @wking, do you have time to look at this? If not, I'm happy to review and publish a new version, I just don't want to step on your toes :)

**Comment by kemitchell** [comment]
Thanks, @carols10cents!

**Comment by wking** [comment]
I've been super-busy, feel free to take it away ;)

**Comment by carols10cents** [comment]
Looks great, thank you so much! I will have a new version published in a bit, and then I will work on updating crates.io.

**Comment by kemitchell** [comment]
Thanks again, @carols10cents!

**Pull request merged**
